let bookArchive = [
  {
    id: 1,
    materia: "Matematica",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://github.com/ViktorChs",
  },
  {
    id: 2,
    materia: "Matematica",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_4.PNG",
    link: "https://github.com/ViktorChs",
  },
  {
    id: 3,
    materia: "Matematica",
    nombre: "a Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://github.com/ViktorChs",
  },
  {
    id: 4,
    materia: "Matematica",
    nombre: "b Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_4.PNG",
    link: "https://github.com/ViktorChs",
  },
  {
    id: 5,
    materia: "Matematica",
    nombre: "investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://github.com/ViktorChs",
  },
  {
    id: 6,
    materia: "Programacion",
    nombre: "Humano demaciado humano",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_4.PNG",
    link: "https://github.com/ViktorChs",
  },
  {
    id: 7,
    materia: "Programacion",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://github.com/ViktorChs",
  },
  {
    id: 8,
    materia: "Programacion",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_4.PNG",
    link: "https://github.com/ViktorChs",
  },
  {
    id: 9,
    materia: "Programacion",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://github.com/ViktorChs",
  },
  {
    id: 10,
    materia: "Programacion",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_4.PNG",
    link: "https://github.com/ViktorChs",
  },
  {
    id: 11,
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://github.com/ViktorChs",
  },
  {
    id: 12,
    materia: "Proyecto",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_4.PNG",
    link: "https://github.com/ViktorChs",
  },
  {
    id: 13,
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://github.com/ViktorChs",
  },
  {
    id: 14,
    materia: "Proyecto",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_4.PNG",
    link: "https://github.com/ViktorChs",
  },
];
